### ISSUE TITLE
How to Speak a Language without Knowing It

### ISSUE THREAD

**Issue by alphadl** [THUNLP-MT/MT-Reading-List#20]
* ACL 2014
* PDF link: https://aclanthology.info/papers/P14-2046/p14-2046
* MT, this paper develops a system that lets people overcome language barriers by letting them
speak a language they do not know. That system accepts text entered by a user,
translates the text, then converts the translation into a phonetic spelling in the user’s
own orthography. 
* For example: input:"*interesting*"-->output:"*因吹斯听*"

**Comment by minicheshire** [comment]
I find that this paper is more likely to be about machine **transliteration** instead of machine translation. In fact I was skimming through the TACL18 when I find the paper [Leveraging Orthographic Similarity for Multilingual Neural Transliteration](http://aclweb.org/anthology/Q18-1022).
According to the definition, a translation tells you the meaning of words in another language; a transliteration doesn't tell you the meaning of the words, but it helps you pronounce them (see https://www.familytreemagazine.com/premium/now-what-translation-vs-transliteration/). It's the first time that I came to know this fascinating topic :P
